version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=rlence
      - POSTGRES_PASSWORD=rlencepassword

  back:
    container_name: backend
    build: ./back
    image: node:14.0.0
    working_dir: /usr/local/app
    volumes:
      - ./back/:/usr/local/app
      - /usr/local/app/node_modules/
      - /usr/local/share/.cache/yarn/
    command: bash -c "yarn install && yarn dev"
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    env_file:
       - .env.development

  front:
    container_name: front
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - back
    working_dir: /usr/src/app
    command: bash -c "yarn install && yarn start"
    volumes:
      - ./front:/usr/src/app